# Generated by Django 3.0.8 on 2020-07-04 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='platforms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('site_url', models.CharField(max_length=300)),
                ('image_url', models.CharField(max_length=1000)),
                ('platform_type', models.CharField(choices=[('exchange', 'Exchange'), ('coin', 'Coin'), ('give_away', 'Give Away')], max_length=100)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('video_url', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('createdon', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('request', models.CharField(max_length=1000)),
                ('createdon', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('review', models.TextField()),
                ('createdon', models.DateField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.platforms')),
            ],
        ),
    ]
