# Generated by Django 3.0.8 on 2020-07-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200705_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platforms',
            old_name='video_url',
            new_name='video_id',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='platforms',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
