# Generated by Django 3.0.8 on 2020-07-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200705_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='platforms',
            name='api_name',
            field=models.CharField(blank=True, help_text='Provide if the name in API used is different then name given above', max_length=300),
        ),
    ]
