# Generated by Django 3.0.8 on 2020-07-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_platforms_api_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='request',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='createdon',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
