# Generated by Django 3.0.8 on 2020-07-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200706_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platforms',
            name='createdon',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='createdon',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
