# Generated by Django 3.0.8 on 2020-07-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200707_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, upload_to='photos/%Y/%m/%d'),
        ),
    ]
