# Generated by Django 3.0.8 on 2020-07-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_review_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('coin', models.CharField(max_length=300)),
                ('exchange', models.CharField(max_length=300)),
                ('network_type', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
