# Generated by Django 3.0.8 on 2020-09-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200709_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='is_problem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='is_problem_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='parent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='problem_type',
            field=models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Scam'), (2, 'Problems with withdrawals'), (3, 'Problems with deposits'), (4, 'Problems with KYC'), (5, 'Problems with Trade'), (6, 'Problems with Coins/Tokens'), (7, 'Problems with Customer Service'), (8, 'Problems with wallets'), (9, 'Other Problems')], default=0),
        ),
    ]
